logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc.:
            bind: trace
      flywaydb:
        core: info
      springframework:
        security: debug
    com:
      zaxxer:
        hikari: info
spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:shop}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT:6379}
  security:
    user:
      name: admin
      password: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8080
