name: Shop API

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
      - hotfix-*

concurrency:
  group: shop-api/${{ github.workflow }}@${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Gradle setup and cache
        uses: gradle/actions/setup-gradle@v4


      - name: Build and Test
        run: ./gradlew --no-daemon clean check

      - name: Upload test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-reports
          path: build/reports/tests/test

      - name: Upload JAR (on success)
        uses: actions/upload-artifact@v4
        with:
          name: shop-api-jar
          path: build/libs/*.jar


